services:
  google-auth:
    build: .
    env_file:
      - .env
    command: npm run start:prod
    ports:
      - "3001:3001"
    networks:
      - authNet
    depends_on:
      - mysqlDb

  mysqlDb:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - authNet
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/mysql_database
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_TCP_PORT=3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

      - ./secrets/mysql_root_password:/run/secrets/mysql_root_password
      - ./secrets/mysql_database:/run/secrets/mysql_database
      - ./secrets/mysql_user:/run/secrets/mysql_user
      - ./secrets/mysql_password:/run/secrets/mysql_password

networks:
  authNet: {}

volumes:
  mysql_data:
